name: albarq_tools
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # file_picker: ^5.2.2
  mobile_scanner: ^2.0.0
  responsive_framework: ^0.2.0 
  just_audio: ^0.9.30
  shared_preferences: ^2.0.15
  http: ^0.13.5
  package_info_plus: ^3.0.1
  url_launcher: ^6.1.4

  
  json_annotation: ^4.7.0
  dio: ^4.0.6
  retrofit: ^3.3.1
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/imgs/
